name:                ffmpeg-wrapper-worker
version:             0.1.0.0
github:              "trajkovvlatko/ffmpeg-wrapper-worker"
license:             BSD3
author:              "Vlatko Trajkov"
maintainer:          "trajkovvlatko@gmail.com"
copyright:           "2022 Vlatko Trajkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/trajkovvlatko/ffmpeg-wrapper-worker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ffmpeg-wrapper-worker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ffmpeg-wrapper-worker

tests:
  ffmpeg-wrapper-worker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ffmpeg-wrapper-worker
